add idiom 259
tokiwa-software/fuzion-idioms pull request #142
Opened 2024-06-18 15:40 UTC by simonvonhackewitz

Idiom 259: [Split on several separators](https://www.programming-idioms.org/idiom/259/split-on-several-separators)

2024-06-20 11:32 UTC, fridis requested changes

2024-06-20 11:32 UTC, fridis commented on src/idiom259.fuzion
> +parts := s.replace("_", ",").replace("-", ",").split(",")
Call syntax `(a b c)` is preferred over `a(b,c)`, so better use this
```suggestion
parts := s.replace "_"  ","
          .replace "-"  ","
          .split ","
```

2024-06-20 11:32 UTC, fridis commented on src/idiom259ex.fz
> +          say "\"$s\" : {s.replace("_", ",").replace("-", ",").split(",")}"
better use exactly the code from `idiom259.fuzion`, i.e., `parts := s.replace...`

2024-06-25 09:41 UTC, michaellilltokiwa commented
Please add a variant using `String.fields_func`

2024-06-27 07:13 UTC, michaellilltokiwa approved these changes

2024-06-27 07:13 UTC, michaellilltokiwa commented
Nice

2024-06-27 07:13 UTC, merged