add idiom 283 Split with a custom string separator
tokiwa-software/fuzion-idioms pull request #145
Opened 2024-06-19 14:54 UTC by simonvonhackewitz

[Idiom 283](https://www.programming-idioms.org/idiom/283/split-with-a-custom-string-separator)

2024-06-20 11:43 UTC, fridis requested changes

2024-06-20 11:43 UTC, fridis commented on src/idiom283.fuzion
> +parts := s.split(sep)
avoid `()`
```suggestion
parts := s.split sep
```

2024-06-20 11:44 UTC, fridis requested changes
avoid parentheses

2024-07-01 07:59 UTC, michaellilltokiwa approved these changes

2024-07-01 07:59 UTC, merged